openapi: 3.0.0
info:
  title: ALICE Bookkeeping
  version: 0.0.0
servers:
- url: /api
paths:
  /:
    get:
      operationId: getServerInformation
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiInformation'
          description: API information
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Service Unavailable
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unexpected Error
      summary: Get server information
  /logs:
    get:
      operationId: listLogs
      parameters:
      - description: Filter logs by their origin
        explode: true
        in: query
        name: filter[origin]
        required: false
        schema:
          enum:
          - human
          - process
          type: string
        style: form
      - description: The number of items to skip before starting to collect the result
          set.
        explode: true
        in: query
        name: page[offset]
        required: false
        schema:
          default: 0
          minimum: 0
          type: integer
        style: form
      - description: The numbers of items to return.
        explode: true
        in: query
        name: page[limit]
        required: false
        schema:
          default: 100
          maximum: 100
          minimum: 1
          type: integer
        style: form
      - description: The sort order of the returned items.
        explode: false
        in: query
        name: sort
        required: false
        schema:
          default:
          - -id
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfLogsResponse'
          description: Expected response to a valid request.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad Request
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unexpected Error
      summary: List all logs
      tags:
      - log
    post:
      operationId: createLog
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogResponse'
          description: Expected response to a valid request.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad Request
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unexpected Error
      summary: Adds a new log
      tags:
      - log
  /logs/{logId}:
    get:
      operationId: getLogById
      parameters:
      - description: The id of the log to retrieve
        explode: false
        in: path
        name: logId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogResponse'
          description: Expected response to a valid request.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Not Found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unexpected Error
      summary: Gets a log by Id
      tags:
      - log
  /logs/{logId}/tags:
    get:
      operationId: listTagsByLogId
      parameters:
      - description: The id of the log to retrieve
        explode: false
        in: path
        name: logId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfTagsResponse'
          description: Expected response to a valid request.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Not Found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unexpected Error
      summary: Lists all tags associated with a log
      tags:
      - log
      - tag
  /status:
    get:
      operationId: getDeployInformation
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeployInformation'
          description: Deploy information
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Service Unavailable
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unexpected Error
      summary: Get deploy information
  /tags:
    get:
      operationId: listTags
      parameters:
      - description: The number of items to skip before starting to collect the result
          set.
        explode: true
        in: query
        name: page[offset]
        required: false
        schema:
          default: 0
          minimum: 0
          type: integer
        style: form
      - description: The numbers of items to return.
        explode: true
        in: query
        name: page[limit]
        required: false
        schema:
          default: 100
          maximum: 100
          minimum: 1
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfTagsResponse'
          description: Expected response to a valid request.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad Request
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unexpected Error
      summary: List all tags
      tags:
      - tag
    post:
      operationId: createTag
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagResponse'
          description: Expected response to a valid request.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad Request
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Conflict
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unexpected Error
      summary: Adds a new tag
      tags:
      - tag
  /tags/{tagId}:
    get:
      operationId: getTagById
      parameters:
      - description: The id of the tag to retrieve
        explode: false
        in: path
        name: tagId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagResponse'
          description: Expected response to a valid request.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Not Found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unexpected Error
      summary: Gets a tag by Id
      tags:
      - tag
  /tags/{tagId}/logs:
    get:
      operationId: getLogsByTagId
      parameters:
      - description: The id of the tag to retrieve
        explode: false
        in: path
        name: tagId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfLogsResponse'
          description: Expected response to a valid request.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Not Found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unexpected Error
      summary: Gets all logs with this tag id
      tags:
      - tag
components:
  parameters:
    FilterOrigin:
      description: Filter logs by their origin
      explode: true
      in: query
      name: filter[origin]
      required: false
      schema:
        enum:
        - human
        - process
        type: string
      style: form
    LogId:
      description: The id of the log to retrieve
      explode: false
      in: path
      name: logId
      required: true
      schema:
        format: int64
        type: integer
      style: simple
    PageLimit:
      description: The numbers of items to return.
      explode: true
      in: query
      name: page[limit]
      required: false
      schema:
        default: 100
        maximum: 100
        minimum: 1
        type: integer
      style: form
    PageOffset:
      description: The number of items to skip before starting to collect the result
        set.
      explode: true
      in: query
      name: page[offset]
      required: false
      schema:
        default: 0
        minimum: 0
        type: integer
      style: form
    SortLogs:
      description: The sort order of the returned items.
      explode: false
      in: query
      name: sort
      required: false
      schema:
        default:
        - -id
        items:
          type: string
        type: array
      style: form
    TagId:
      description: The id of the tag to retrieve
      explode: false
      in: path
      name: tagId
      required: true
      schema:
        format: int64
        type: integer
      style: simple
  responses:
    ArrayOfLogs:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ArrayOfLogsResponse'
      description: Expected response to a valid request.
    ArrayOfTags:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ArrayOfTagsResponse'
      description: Expected response to a valid request.
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Bad Request
    Conflict:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Conflict
    Log:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LogResponse'
      description: Expected response to a valid request.
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Not Found
    ServiceUnavailable:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Service Unavailable
    Tag:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TagResponse'
      description: Expected response to a valid request.
    UnexpectedError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Unexpected Error
  schemas:
    ApiInformation:
      description: API information
      example:
        name: name
        version: version
      properties:
        name:
          description: Name of the API
          type: string
        version:
          description: Version of the API
          type: string
      required:
      - name
      - version
      type: object
    ArrayOfLogs:
      description: A list of Log objects.
      items:
        $ref: '#/components/schemas/Log'
      type: array
    ArrayOfLogsResponse:
      description: Response containing multiple logs.
      example:
        data:
        - origin: human
          title: title
          entryId: 0
          tags:
          - createdAt: createdAt
            updateAt: updateAt
            id: 6
            text: text
          - createdAt: createdAt
            updateAt: updateAt
            id: 6
            text: text
        - origin: human
          title: title
          entryId: 0
          tags:
          - createdAt: createdAt
            updateAt: updateAt
            id: 6
            text: text
          - createdAt: createdAt
            updateAt: updateAt
            id: 6
            text: text
      properties:
        data:
          description: A list of Log objects.
          items:
            $ref: '#/components/schemas/Log'
          type: array
      required:
      - data
      type: object
    ArrayOfTags:
      description: A list of Tag objects.
      items:
        $ref: '#/components/schemas/Tag'
      type: array
    ArrayOfTagsResponse:
      description: Response containing multiple tags.
      example:
        data:
        - createdAt: createdAt
          updateAt: updateAt
          id: 6
          text: text
        - createdAt: createdAt
          updateAt: updateAt
          id: 6
          text: text
      properties:
        data:
          description: A list of Tag objects.
          items:
            $ref: '#/components/schemas/Tag'
          type: array
      required:
      - data
      type: object
    DeployInformation:
      description: Deploy information
      example:
        start: 6.027456183070403
        age: 0.8008281904610115
      properties:
        age:
          description: The number of seconds that the server is online.
          type: number
        start:
          description: The unix timestamp of the moment that the the server went online.
          type: number
      required:
      - age
      - start
      type: object
    Error:
      description: An Error object.
      properties:
        status:
          description: The HTTP status code applicable to this problem.
          type: string
        title:
          description: A short, human-readable summary of the problem.
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
      required:
      - status
      - title
      type: object
    Errors:
      description: A list of Error objects.
      properties:
        errors:
          description: A list of Error objects.
          items:
            $ref: '#/components/schemas/Error'
          minItems: 1
          type: array
      required:
      - errors
      type: object
    Log:
      description: Describes an intervention or an event that happened.
      example:
        origin: human
        title: title
        entryId: 0
        tags:
        - createdAt: createdAt
          updateAt: updateAt
          id: 6
          text: text
        - createdAt: createdAt
          updateAt: updateAt
          id: 6
          text: text
      properties:
        entryId:
          description: Id of the log.
          format: int64
          type: integer
        title:
          description: Title of the log.
          type: string
        origin:
          description: Type of creator.
          enum:
          - human
          - process
          type: string
        tags:
          description: A list of Tag objects.
          items:
            $ref: '#/components/schemas/Tag'
          type: array
      required:
      - entryId
      - origin
      - tags
      - title
      type: object
    LogResponse:
      description: Response containing a single log.
      example:
        data:
          origin: human
          title: title
          entryId: 0
          tags:
          - createdAt: createdAt
            updateAt: updateAt
            id: 6
            text: text
          - createdAt: createdAt
            updateAt: updateAt
            id: 6
            text: text
      properties:
        data:
          $ref: '#/components/schemas/Log'
      required:
      - data
      type: object
    Tag:
      additionalProperties: false
      description: A label attached to something for the purpose of identification.
      example:
        createdAt: createdAt
        updateAt: updateAt
        id: 6
        text: text
      properties:
        id:
          description: Id of the tag.
          format: int64
          type: integer
        text:
          description: The label value of the tag.
          type: string
        createdAt:
          description: Date when the tag was created.
          type: string
        updateAt:
          description: Date when the tag was last updated.
          type: string
      required:
      - id
      - text
      type: object
    TagResponse:
      description: Response containing a single tag.
      example:
        data:
          createdAt: createdAt
          updateAt: updateAt
          id: 6
          text: text
      properties:
        data:
          $ref: '#/components/schemas/Tag'
      required:
      - data
      type: object
